theme: jekyll-theme-architect

title: [metro-xmlstreambuffer]
description: [XML Stream Buffer]

# sidebar links url
links:
  source: https://github.com/javaee/metro-xmlstreambuffer
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

